name: ms-qc-monitoring
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.13
  - numpy=2.2
  - pandas=2.3
  - scikit-learn=1.7
  - pytorch=2.6
  - matplotlib=3.10
  - jupyter
  - nbformat=5.10
  - r-base=4.2
  - r-readxl=1.4
